theme: jekyll-theme-minimal
title: Violeta Epardo's homepage
description: Bookmark this to keep an eye on my project updates!
name: Violeta Epardo
avatar: https://avatars.githubusercontent.com/u/70412439?v=4
